controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    test_controller:
      type: warrior_controller/Testcontroller
    wheel_balance_controller:
      type: warrior_controller/WheelBalancingController

test_controller:
  ros__parameters:
    joint1_name: test_joint1
    joint2_name: test_joint2
wheel_balance_controller:
    ros__parameters:
      joint1_name: imu
      joint2_name: left_9025
      joint3_name: right_9025