/**:
  ros__parameters:
    update_rate: 250
controller_manager:
  ros__parameters:
    test_controller:
      type: warrior_controller/Testcontroller
    wheel_balance_controller:
      type: warrior_controller/WheelBalancingController

test_controller:
  ros__parameters:
    joint1_name: test_joint1
    joint2_name: test_joint2
wheel_balance_controller:
    ros__parameters:
      joint1_name: imu
      joint2_name: left_9025
      joint3_name: right_9025
      joint_Go_LF_name: Go1_LF
      joint_Go_LB_name: Go1_LB 
      joint_Go_RF_name: Go1_RF
      joint_Go_RB_name: Go1_RB

      body_mg: 35.84 # half body mass
      
      fy_left_pid_p: 1250.0
      fy_left_pid_i: 0.0 
      fy_left_pid_d: 1050.0

      fy_right_pid_p: 1250.0
      fy_right_pid_i: 0.0
      fy_right_pid_d: 1050.0

      x_q: 100.0
      x_dot_q: 1.1
      theta_q: 100.0
      theta_dot_q: 1.1
      fai_q: 100.0
      fai_dot_q: 1.1

      r1: 1.0
      r2: 1.0
                                                                                       
      k00:   12.0061
      k01:   9.2669
      k02:  -2.0416
      k03:   7.7998
      k04:  44.2023 
      k05:  -10.2829
             
      k10:  -0.6616
      k11:  -0.7187
      k12:  -1.5142
      k13:  -0.4230
      k14:  -1.3338
      k15:  -4.3509    