#vmc output
float64 left_t_one
float64 left_t_two
#vmc input
float64 left_tp
float64 left_f
#five bar linkage
float64 left_fai_one
float64 left_fai_four
#pid output
float64 left_target_l
float64 left_actual_l
float64 left_pid_fy
float64 left_p_out
float64 left_i_out
float64 left_d_out

#vmc output
float64 right_t_one
float64 right_t_two
#vmc input
float64 right_tp
float64 right_f
#five bar linkage
float64 right_fai_one
float64 right_fai_four
#pid output
float64 right_target_l
float64 right_actual_l
float64 right_pid_fy
float64 right_p_out
float64 right_i_out
float64 right_d_out




